questionnaire/urls.py
from django.urls import path
from questionnaire import views
from .views import (
    QuestionnaireListView,
    QuestionnaireCreateView
)

urlpatterns = [
    path("",views.home,name="home"),
    path("about/",views.about,name="about"),
    path("listview/",QuestionnaireListView.as_view(),name="questionnaire-list"),
    path("createview/",QuestionnaireCreateView.as_view(),name="questionnaire-create"),

]
    

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("questionnaire.urls")),
]

questionnaire/models.py
from django.db import models
from django.utils import timezone

gender_choices = [
    ('Male', "Male"),
    ('Female', "Female")
]

question_choices = [
    (None, ""),
    ('Yes', "Yes"),
    ('No', "No")
]

improve_choices = [
    ('Welcome', "Welcome"),
    ('Room', "Room"),
    ('Food', "Food"),
    ('Guiding', "Guiding")
]

welcome_choices = [
    ('Check-in', "Check-in"),
    ('Waiter', "Waiter"),
]
room_choices = [
    ('Cleanness', "Cleanness"),
    ('Bed', "Bed"),
    ('Bathroom', "Bathroom"),
]
food_choices = [
    ('Breakfast', "Breakfast"),
    ('Lunch', "Lunch"),
    ('Dinner', "Dinner"),
]
guiding_choices = [
    ('Kindness', "Kindness"),
    ('Knowledge', "Knowledge"),
    ('Vehichle', "Vehichle"),
]


class QuestionnaireResponse(models.Model):
    
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=10,choices=gender_choices,default="Male")
    age = models.IntegerField()
    nationality = models.CharField(max_length=50)

    question_1 = models.CharField("Has your trip exceeded your expectations?",max_length=5,choices=question_choices,blank=False,default="")
    question_2 = models.TextField("What was the most memorable moment with us?", max_length=200,blank=True)
    question_3 = models.CharField("Where can we improve?",max_length=20, choices=improve_choices, blank=True,default="")

    
    question_3_subquestion_1 = models.CharField("Welcome improvements",max_length=50,choices=welcome_choices, blank=True, default="")
    question_3_subquestion_2 = models.CharField("Room improvements",max_length=50,choices=room_choices, blank=True, )
    question_3_subquestion_3 = models.CharField("Food improvements",max_length=50,choices=food_choices, blank=True)
    question_3_subquestion_4 = models.CharField("Guiding improvements",max_length=50,choices=guiding_choices, blank=True)
    

    date_published = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return("Questionnaire response "+str(self.pk))



# Create your models here.

questionnaire/forms.py
from django import forms
from .models import QuestionnaireResponse



class QuestionnaireForm(forms.ModelForm):
    class Meta:
        model = QuestionnaireResponse
        fields = ["name","gender","age","nationality","question_1","question_2","question_3","question_3_subquestion_1","question_3_subquestion_2","question_3_subquestion_3","question_3_subquestion_4"]
        widgets = {
            'question_3':forms.CheckboxSelectMultiple(),
            'question_3_subquestion_1':forms.RadioSelect(),
        }

questionnaire/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    FormView,
)
from .models import QuestionnaireResponse
from .forms import QuestionnaireForm

def home(request):
    return render(request, "questionnaire/home.html")

def about(request):
    return render(request, "questionnaire/about.html")


class QuestionnaireListView(ListView):
    model = QuestionnaireResponse
    context_object_name = "questionnaire"
    template_name = "questionnaire/list_view.html"
    ordering = ["-date_published"]


class QuestionnaireCreateView(CreateView):
    form_class = QuestionnaireForm
    template_name = "questionnaire/questionnaireresponse_form.html"
    success_url = "/listview/"

questionnaire/templates/questionnaire/about.html
{% extends "questionnaire/base.html" %}
{% block content %}
    <h1>This is the About page</h1>
 
{% endblock content %}

questionnaire/templates/questionnaire/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Elewana Guest Experience Card</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Elewana Feedback Form</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent"> 
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'questionnaire-list' %}">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'questionnaire-create' %}">Create</a>
                </li>
                {% if request.user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="/admin/">Admin</a>
                </li>
                {% endif %}
        </div>
    </nav>
    
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script>
    $(document).ready(function(){
        $('#div_id_question_2').hide()
        $('#div_id_question_3').hide()
        $('#div_id_question_3_subquestion_1').hide()
        $('#div_id_question_3_subquestion_2').hide()
        $('#div_id_question_3_subquestion_3').hide()
        $('#div_id_question_3_subquestion_4').hide()

        $("#id_question_1").change(function(){
            value = $("#id_question_1 :selected").text()
            
            if(value == "Yes") {
                $('#div_id_question_2').show()
                $('#div_id_question_3').hide()
            } else if (value == "No") {
                $('#div_id_question_2').hide()
                $('#div_id_question_3').show()
            } else if (value == "---------") {
                $('#div_id_question_2').hide()
                $('#div_id_question_3').hide()
            }
        
        $("#id_question_3_1").change(function(){
            if($(this).is(":checked")){
                $('#div_id_question_3_subquestion_1').show()
            } else if($(this).is(":not(:checked)")){
                $('#div_id_question_3_subquestion_1').hide()
            }
        })
        $("#id_question_3_2").change(function(){
            if($(this).is(":checked")){
                $('#div_id_question_3_subquestion_2').show()
            } else if($(this).is(":not(:checked)")){
                $('#div_id_question_3_subquestion_2').hide()
            }
        })
        $("#id_question_3_3").change(function(){
            if($(this).is(":checked")){
                $('#div_id_question_3_subquestion_3').show()
            } else if($(this).is(":not(:checked)")){
                $('#div_id_question_3_subquestion_3').hide()
            }
        })
        $("#id_question_3_4").change(function(){
            if($(this).is(":checked")){
                $('#div_id_question_3_subquestion_4').show()
            } else if($(this).is(":not(:checked)")){
                $('#div_id_question_3_subquestion_4').hide()
            }
        })
           

        });


    });
    
    </script>
</body>
</html>

questionnaire/templates/questionnaire/home.html
{% extends "questionnaire/base.html" %}
{% block content %}
    <h1>Welcome To Elewana</h1>
<p>Click Create button</p>
 
{% endblock content %}

questionnaire/templates/questionnaire/list_view.html
{% extends "questionnaire/base.html" %}
{% block content %}
    {% for question in questionnaire %}
        <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">questionnaire response {{ question.pk }}</h5>
              <p>Name: {{ question.name }}</p>
              <p>Gender: {{ question.gender }}</p>
              <p>Age: {{ question.age }}</p>
              <p>Nationality: {{ question.nationality }}</p>
              <p>Visit been exceeded: {{ question.question_1 }}</p>
              <p>Most memorable experience: {{ question.question_2 }}</p>
            </div>
          </div>
    {% endfor %}
{% endblock content %}

questionnaire/templates/questionnaire/questionnaireresponse_form.html
{% extends "questionnaire/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Please fill in this form</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
 
{% endblock content %}